### ISSUE TITLE
Boost library is not getting installed

### ISSUE THREAD

**Issue by Shivangi1010** [legolason/PyIICCF#1]
during ./bootstrap command using python2.7 version. The following error is coming:
unicode /ICU support for Boost.Regex?...not found.

**Comment by legolason** [comment]
make sure your version is 1.64, since CARMA only work with very old version.

**Comment by Shivangi1010** [comment]
Yes, I did use the older version.

**Comment by Shivangi1010** [comment]
after installing all the required libraries for boost, it seems not to be installed properly as it gets failed after 15 minutes.

**Comment by legolason** [comment]
what do you mean by failed after 15 min? when you install the boost, you may need to move some files to the proper place as the default directory may not work

**Comment by Shivangi1010** [comment]
I meant initially that it is not getting successfully installed after bootstrapping and building when I am installing the boost. Regarding moving the files to a proper place as instructed by you (under \home\user\softwares\), I have been following the exact steps.
Note: I have python2 within an environment.
Although the armadillo library was installed correctly.
Is it something to do with my python version, GCC compiler?

**Comment by legolason** [comment]
Could you paste the error here? boost is indeed the pain in the neck. CARAM pack is still using this old package.  If your system is ubuntu, it may be easier than MacOS. 

For a proper directory: I mean the boost sometimes looking for a director boost/../../  but the default may have something like boost_16_4, you need to change the directory

**Comment by Shivangi1010** [comment]
Hi,
Thank you for your reply.
I will describe what exactly I did.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
I downloaded boost version 1.64 (https://boostorg.jfrog.io/artifactory/main/release/1.64.0/source/) boost_1_64_0.tar.gz and untar in the home directory /home/shivangi/
then, I did ./bootstrap.sh —prefix=/home/user/softwares/boost
./b2 install
and it gets successfully installed.
It says at the end -- The Boost C++ Libraries were successfully built!

The following directory should be added to compiler include paths:

    /home/shivangi/boost_1_64_0

The following directory should be added to linker library paths:

    /home/shivangi/boost_1_64_0/stage/lib

the, opened the .bashrc file and added export BOOST_DIR=/home/user/softwares/boost  (although it says /home/shivangi/boost_1_64_0 but I did put that also and it was not working and unfortunately /home/softwares/ also did not have created boost, so I went to /home/user/softwares/ directory and moved some files. )
Now, the boost is under /home/user/softwares/ having include and lib folders

Then, I downloaded and followed exact same step given in (https://github.com/legolason/PyIICCF/blob/master/install_ubuntu) and it successfully got placed in the /home/user/softwares/ directory I do not have to move files.
It says -- Build files have been written to: /home/shivangi/armadillo-9.900.2.

I have added the armadilo directory in the bash file as:
export BOOST_DIR=/home/user/softwares/boost
export CARMA_DIR=/home/shivangi/carma_pack
export ARMADILLO_DIR=/home/user/softwares/armadillo
export NUMPY_DIR=/home/shivangi/anaconda3/envs/env_py2/lib/python2.7/site-packages
export LD_LIBRARY_PATH=/home/user/softwares/boost/lib:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH=/home/user/softwares/armadillo/lib:${LD_LIBRARY_PATH}

(unfortunately, when echoed the $LD_LIBRARY_PATH , it says bash: /home/user/softwares/armadillo/lib:/home/user/softwares/boost/lib:: No such file or directory. 

I cloned carma_pack and under src I installed setup.py, everything happened correctly.
Now, when I am running the testcarma.py program: error is ImportError: /home/shivangi/anaconda3/envs/env_py2/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/user/softwares/boost/lib/libboost_python.so.1.64.0)
 
I moved libstdc++.so.6.0.29 to /home/shivangi/anaconda3/envs/env_py2/lib/ . However, it is still giving the same error.

**Comment by Shivangi1010** [comment]
I could not get the normal installation to work, So, I installed using dockerfile and it works.
Although just one question, in the code tutorial.ipynb there is one parameter scale_simLC is not working: giving the following error:
TypeError: ICCF() got an unexpected keyword argument 'scale_simLC'

**Comment by legolason** [comment]
Oh, that is old version keyword, just delete it

**Comment by Shivangi1010** [comment]
okay, thanks!
